config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "posts#index"

  resources :posts
  resources :users
  resources :sessions



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :password, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts=Post.all
  end

  def new
    @post=Post.new
  end

  def create
    @post=Post.new(post_params)

    if @post.save
      redirect_to posts_path
    else
      render new, status: :unprocessable_entity
    end

  end

  private 

  def post_params
    params.require(:post).permit(:author,:body)
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else 
      render :new, status: :unprocessable_entity
    end 
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password_digest,:password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clubhouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
<% @posts.each do |post|%>
  <li>
  <%= post.author if session[:user_id] != nil %><br>
  <%= post.body %><br>
  </li>
<% end %>
</ul>

<%= link_to "New Post", new_post_path %> <br>
<%= link_to "Login to see author name", new_session_path %>

app/views/posts/new.html.erb
<%= form_with model: @post do |form| %>

  <div>
    <%= form.label :author %><br>
    <%= form.text_field :author, value: "#{User.find(session[:user_id]).name}" %><br><br>
  </div>

  <div>
    <%= form.label :body, "Enter your post" %><br>
    <%= form.text_field :body %><br><br>
  </div>

  <div>
    <%= form.submit "Create" %>
  </div>


<% end %>

app/views/users/new.html.erb
<%= form_with model: @user do |form| %>

 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Enter your name" %><br>
    <%= form.text_field :name %><br><br>
  </div>

  <div>
    <%= form.label :email, "Enter your Email" %><br>
    <%= form.text_field :email %><br><br>
  </div>

  <div>
    <%= form.label :password, "Enter your Password" %><br>
    <%= form.password_field :password %><br><br>
  </div>

  <div>
    <%= form.label :password_confirmation, "Enter your Password again" %><br>
    <%= form.password_field :password_confirmation %><br><br>
  </div>


  <div>
    <%= form.submit "Submit" %>
  </div>


<% end %>